=== justicecanada/lims-xml-dtd/TOPS/TOPS.dtd
<?aptxml encoding="utf-8"?>

<!ELEMENT TOPS (Statute)+ >

<!ELEMENT Statute (Title, ChapterNumber?, TitleChanged?, OtherLangTitle*, Minister*, LongTitle?, (Item | List | Section | Schedule |Heading | General | Terminology | Transitional | Repeal | Application | CoordinatingAmendment | ConditionalAmendment | CIF | Convention)*) >
<!ATTLIST Statute FlicsId CDATA #IMPLIED 
				FlicsAlpha	CDATA #IMPLIED>

<!ELEMENT Title (#PCDATA | Emphasis | Sup)* >
<!ELEMENT ChapterNumber (#PCDATA | Emphasis | Sup)* >
<!ELEMENT TitleChanged (#PCDATA | Text)* >
<!ELEMENT OtherLangTitle (#PCDATA | Emphasis | Sup)* >
<!ELEMENT Minister (Text)* >
<!ELEMENT LongTitle (Label, Text) >

<!ELEMENT Section (Label, Text, List?) >

<!ELEMENT Schedule (Label, Text?, List?) >

<!ELEMENT Heading (Label, Text?) >

<!ELEMENT Label (#PCDATA | Emphasis)* >

<!ELEMENT Sup (#PCDATA) >

<!ELEMENT List (Item)+ >

<!ELEMENT Item (Label?, Text, List?) >

<!ELEMENT Text (#PCDATA | Emphasis | Sup | XRefExternal | Amendment)* >

<!ELEMENT Amendment (Source | CIFInfo)* >

<!ELEMENT Source (#PCDATA | Emphasis | Sup | XRefExternal)* >
<!ELEMENT CIFInfo (#PCDATA | Emphasis | Sup | XRefExternal | Date | CIFProv)* >

<!ELEMENT Date (#PCDATA) >
<!ELEMENT CIFProv (#PCDATA) >

<!ELEMENT CIF (Text | List)* >
<!ELEMENT Terminology (Text)* >
<!ELEMENT Transitional (Text)* >
<!ELEMENT Application (Text)* >
<!ELEMENT General (Text)* >
<!ELEMENT Repeal (Text)* >
<!ELEMENT CoordinatingAmendment (Text)* >
<!ELEMENT ConditionalAmendment (Text)* >

<!ELEMENT Convention (Text | List | Section | Schedule |Heading | General | Terminology | Transitional | Repeal | CoordinatingAmendment | CIF)* >

<!ELEMENT Emphasis (#PCDATA | Emphasis | Sup)* >
<!ATTLIST Emphasis
               style  CDATA    #IMPLIED  >
			   
<!ELEMENT XRefExternal (#PCDATA | Emphasis | Sup)* >
<!ATTLIST XRefExternal
               reference-type  CDATA    #IMPLIED  >

=== justicecanada/lims-xml-dtd/TOPS/tops_template_e.xml
<?xml version="1.0" encoding="UTF-8"?><!--Arbortext, Inc., 1988-2010, v.4002-->
<!DOCTYPE TOPS PUBLIC "-//Justice Canada//DTD TOPS//EN" "TOPS.dtd">
<TOPS xml:lang="en">
    <Statute FlicsAlpha="FlicsAlphaID">
        <Title>Title of Act</Title>
        <ChapterNumber>ChapterNumber</ChapterNumber>
        <OtherLangTitle>Other Language Title</OtherLangTitle>
        <Minister>
            <Text>Minister</Text>
        </Minister>
        <LongTitle>
            <Label>Long Title</Label>
            <Text>Text</Text>
        </LongTitle>
        <Section>
            <Label>2</Label>
            <Text>Text</Text>
        </Section>
        <CIF>
            <Text>CIF Text</Text>
        </CIF>
    </Statute>
</TOPS>

=== justicecanada/lims-xml-dtd/TOPS/tops_template_f.xml
<?xml version="1.0" encoding="UTF-8"?><!--Arbortext, Inc., 1988-2010, v.4002-->
<!DOCTYPE TOPS PUBLIC "-//Justice Canada//DTD TOPS//EN" "TOPS.dtd">
<TOPS xml:lang="fr">
    <Statute FlicsAlpha="FlicsAlphaID">
        <Title>Titre</Title>
        <ChapterNumber>Numéro de chapitre</ChapterNumber>
        <OtherLangTitle>Autre langue Titre</OtherLangTitle>
        <Minister>
            <Text>Ministre</Text>
        </Minister>
        <LongTitle>
            <Label>Titre intégral</Label>
            <Text>Texte</Text>
        </LongTitle>
        <Section>
            <Label>2</Label>
            <Text>Texte</Text>
        </Section>
        <CIF>
            <Text>Texte CIF</Text>
        </CIF>
    </Statute>
</TOPS>
